pool:
  name: Hosted VS2017

trigger:
  - none

steps:
  - powershell: |
      $var = (gci env:*).GetEnumerator() | Sort-Object Name
      $out = ""
      Foreach ($v in $var) {$out = $out + "`t{0,-28} = {1,-28}`n" -f $v.Name, $v.Value}
       
      write-output "dump variables on $env:BUILD_ARTIFACTSTAGINGDIRECTORY\test.md"
      $fileName = "$env:BUILD_ARTIFACTSTAGINGDIRECTORY\test.md"
      set-content $fileName $out
       
      write-output "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Environment Variables;]$fileName"
    displayName: "Publish all build variables"

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: 10.x

  - script: "npm install"
    displayName: "npm Install and Build"

  - script: "npm run cy:verify"
    displayName: "Cypress Verify"

  - script: "npm run cy:run:reporter"
    displayName: "Run Cypress tests"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/cypress-and-azure-devops-*.xml"
